version: '3'

services:
  nodejs:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: NestJS
    command: npm run start:dev
    env_file: .env
    volumes:
      - .:/usr/app
      - /Users/seyha/Documents/Codes/NestJS/pos_image:${IMAGE_PATH_DOCKER}:rw
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB 
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - app-network  
  
  db:
    container_name: mongo_pos
    image: mongo
    hostname: mongo
    env_file: .env
    environment:
      - MONGO_INITDB_DATABASE=$MONGO_DB
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - /Users/seyha/Documents/Codes/NestJS/pos_db:/data/db
    networks:
      - app-network
    ports:
      - "27018:27017"
    restart: unless-stopped

networks:
  app-network:
    driver: bridge